version: "3"

services:

  docker-mysql-db:
    restart: always
    container_name: docker-mysql-db
    image: mysql
    env_file:
      - .env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  sut:
    build:
      context: .
      args:
        NODE_ENV: test
    ports:
      - "8083:83"
    command: npm run test
    depends_on:
      - docker-mysql-db