version: '3'
services:
  docker-mysql-db:
    restart: always
    container_name: docker-mysql-db
    image: mysql
    env_file:
      - .env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  tracer-service:
    restart: on-failure
#    image: matijmic/swa-tracer-service
    build: ./
    expose:
      - "10222"
    ports:
      - 10222:10222
    env_file:
      - tracer-service.env
    depends_on:
      - docker-mysql-db

volumes:
  docker-mysql-db:
